# Python package
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Lizard People of The Hollow Earth Subscription(dbd94eae-ba51-4584-9dfa-f2cbefed36db)'
    appType: 'webAppLinux'
    WebAppName: 'yuebai-flaskpipeline'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App : {{ webAppName }}'
  inputs:
    azureSubscription: $(azureServiceConnectionId)
    appType: webApp
    appName: $(webAppName)
    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
    deploymentMethod: zipDeploy

    # The following parameter is specific to the Flask example code. You may
    # or may not need a startup command for your app.

    startUpCommand: 'startup.txt'
